# Generated by Django 3.1.5 on 2021-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Tag')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Pub date')),
            ],
            options={
                'verbose_name': 'Tag',
                'db_table': 'fastcampus_tag',
            },
        ),
    ]
