# Generated by Django 3.1.5 on 2021-01-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fcuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='User Name')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Time')),
            ],
            options={
                'db_table': 'fastcampus_fcuser',
            },
        ),
    ]
