# Generated by Django 3.1.5 on 2021-01-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published DateTime'),
        ),
    ]
