# Generated by Django 3.1.5 on 2021-01-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20210121_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': 'FC User'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.CharField(default='poungki@gmail.com', max_length=128, verbose_name='User Email'),
            preserve_default=False,
        ),
    ]
