# Generated by Django 3.1.5 on 2021-01-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcuser', '0004_auto_20210122_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('contents', models.TextField(verbose_name='Contents')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Published DateTime')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcuser.fcuser', verbose_name='Writer')),
            ],
            options={
                'verbose_name': 'Board',
                'db_table': 'fastcampus_board',
            },
        ),
    ]
